---
  title: Kattya Cuevas
  description: Software Engineer
  domain: https://kattya.dev
  language: en
  repository: https://github.com/KattyaCuevas/personal-site/
  email: kattya.cuevas@gmail.com
  patreon: KattyaCuevas
  social:
    twitter: KattyaCuevas
    github: KattyaCuevas
    linkedin: KattyaCuevas
    dev: kattyacuevas
    meetup: 198000350
  navigation:
  incremental: false